sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t pankaj/client-img -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=True pankaj/client-img npm run test
after_success:
  - docker build -t pankaj349/multi-client ./client
  - docker build -t pankaj349/multi-nginx ./nginx
  - docker build -t pankaj349/multi-server ./server
  - docker build -t pankaj349/multi-worker ./worker
   #docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #Push Docker Images to Dockerhub
  - docker push pankaj349/multi-client
  - docker push pankaj349/multi-nginx 
  - docker push pankaj349/multi-server
  - docker push pankaj349/multi-worker